### ISSUE TITLE
MrEwok Not Work

### ISSUE THREAD

**Issue by Tonight201010** [MrEwok/EWK_HMMWV#1]
si si t'as vuuuuuuuuuuuuu !

**Comment by MrEwok** [comment]
Ouais ouais j'ai vuuuuuuuuuuu !

**Comment by Tonight201010** [comment]
Et tu vas le corriger ? Parce que bon 3 bières et par terre la tronche dans une flaque, c'est pas fonctionnel la, faut réparer!

**Comment by MrEwok** [comment]
Sa craint pas tkt BB!!

**Comment by Tonight201010** [comment]
Ouai non mais tu fermes pas quoi.
