### ISSUE TITLE
bruits de flammes persistant

### ISSUE THREAD

**Issue by abou84** [MrEwok/EWK_HMMWV#2]
yo Ewok,
Juste un petit truc; en buildant la mission d'hier j'ai fais une fausse manip (comme d'hab) et j'ai supprimé via zeus des humwee detruits. Le pb étant que le bruit des flammes a persisté alors que les vehicules n'étaient plus la.
Si ça peut aider..
Poutous

**Comment by Tonight201010** [comment]
Est-ce que tu a fait fondre des marshmallow du coup ?

**Comment by MrEwok** [comment]
Je vais checker sa mais a priori c'est un bug lié au moteur arma.
